Update packages
npm-check showed quite a few packages as outdated.  This updates all of
those, in addition to adding 'axios' to the dependencies list.
Technically the latter isn't required, but without it, npm-check balks
about the lack of inclusion per Midgard/THORNode code:

```
axios   😟  PKG ERR!  Not in the package.json. Found in: /src/cryptotax-thorchain/MidgardService.ts, /src/cryptotax-thorchain/ThornodeService.ts
```

As a result of these updates, fix variable declarations using
PaginatedQueryTxs interface result, as well as remove timeout
parameter to fetch (it no longer exists and therefore defaults
to infinity, AFAIK):

```
TSError: ⨯ Unable to compile TypeScript:
src/viewblock/Viewblock.ts:58:13 - error TS2353: Object literal may only specify known properties, and 'timeout' does not exist in type 'RequestInit'.

58             timeout: 0,
               ~~~~~~~
src/viewblock/Viewblock.ts:94:13 - error TS2322: Type 'unknown' is not assignable to type 'PaginatedQueryTxs'.

94         let page: PaginatedQueryTxs = await this.getTxs({
               ~~~~
src/viewblock/Viewblock.ts:116:13 - error TS2322: Type 'unknown' is not assignable to type 'PaginatedQueryTxs'.

116             page = await this.getTxs({
                ~~~~
```